apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # namespace: develop
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]  

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-readers
  # namespace: develop
subjects:
  - kind: User
    name: wakababoxing@gmail.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
